services:
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    ports:
      - '6443:443'
    links:
      - openldap
    environment:
       PHPLDAPADMIN_LDAP_HOSTS: openldap

  openldap:
    build: .
    container_name: openldap
    ports:
      - '389:389'
    environment:
      - LDAP_PORT_NUMBER=389
      - LDAP_ALLOW_ANON_BINDING=no
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=mypassword123
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=com
      - LDAP_USERS=alice,bob
      - LDAP_PASSWORDS=alice123,bob123
      - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis,pbkdf2
    volumes:
      - 'openldap_data:/bitnami/openldap'

volumes:
  openldap_data:
    driver: local
