version: '3.3'

services:
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    ports:
      - 6443:443
    links:
      - openldap
    container_name: phpldapadmin-service
    environment:
       PHPLDAPADMIN_LDAP_HOSTS: openldap
    # networks:
    #   - reportportal_default

  openldap:
    build: .
    container_name: openldap
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ORGANISATION: 'ReportPortal'
      LDAP_DOMAIN: 'rp.com'
      LDAP_ADMIN_PASSWORD: 'rpadminpass'
    # networks:
    #   - reportportal_default
    volumes:
      - openldap_data:/bitnami/openldap

volumes:
  openldap_data:
    driver: local

# networks:
#   reportportal_default:
#     external: true
